-- -- 參照 SASD 附錄六：更新已發查經緯度
-- INSERT INTO `RAW_EDEP_DATASET.GEOCODING` (
--   PARTITION_DATE,
--   CUID,
--   SERIAL_NUMBER,
--   CREATED_AT,
--   GEO_TYPE,
--   REQUEST_LONGITUDE,
--   REQUEST_LATITUDE,
--   RESPONSE_PLACE_ID,
--   RESPONSE_ADDRESS,
--   RESPONSE_GLOBAL_CODE,
--   RESPONSE_PLACE_TYPES,
--   RESPONSE_LONGITUDE,
--   RESPONSE_LATITUDE,
--   RESPONSE_COUNTRY,
--   RESPONSE_CITY,
--   RESPONSE_DISTRICT,
--   RESPONSE_WARD,
--   RESPONSE_STREET,
--   BQ_CREATED_TIME,
--   BQ_UPDATED_TIME
-- )
-- WITH latest_hes_application AS (
--   SELECT
--     id,
--     serial_number,
--     created_at,
--     PARTITION_DATE AS partition_date,
--     customer_id,
--     BQ_UPDATED_TIME
--   FROM `RAW_HES_DATASET.APPLICATION`
--   QUALIFY ROW_NUMBER() OVER (
--     PARTITION BY id
--     ORDER BY BQ_UPDATED_TIME DESC
--   ) = 1
-- ),
-- latest_hes_customer AS (
--   SELECT
--     id,
--     cuid
--   FROM `RAW_HES_DATASET.CUSTOMER`
--   QUALIFY ROW_NUMBER() OVER (
--     PARTITION BY cuid
--     ORDER BY BQ_UPDATED_TIME DESC
--   ) = 1
-- ),
-- latest_vmb_apply_info AS (
--   SELECT
--     cuid,
--     ROUND(SAFE_CAST(longitude AS FLOAT64), 4) AS longitude,
--     ROUND(SAFE_CAST(latitude AS FLOAT64), 4) AS latitude
--   FROM `RAW_VMB_DATASET.APPLY_INFO`
--   WHERE SAFE_CAST(longitude AS FLOAT64) IS NOT NULL
--     AND SAFE_CAST(latitude AS FLOAT64) IS NOT NULL
--   QUALIFY ROW_NUMBER() OVER (
--     PARTITION BY cuid
--     ORDER BY BQ_UPDATED_TIME DESC
--   ) = 1
-- ),
-- geocoding_serial_number_list AS (
--   SELECT DISTINCT serial_number
--   FROM `RAW_EDEP_DATASET.GEOCODING`
--   WHERE GEO_TYPE = 'CONTRACT_COORDINATES'
-- ),
-- distinct_coordinates AS (
--   SELECT DISTINCT
--     REQUEST_LONGITUDE,
--     REQUEST_LATITUDE,
--     RESPONSE_PLACE_ID,
--     RESPONSE_ADDRESS,
--     RESPONSE_GLOBAL_CODE,
--     RESPONSE_PLACE_TYPES,
--     RESPONSE_LONGITUDE,
--     RESPONSE_LATITUDE,
--     RESPONSE_COUNTRY,
--     RESPONSE_CITY,
--     RESPONSE_DISTRICT,
--     RESPONSE_WARD,
--     RESPONSE_STREET
--   FROM `RAW_EDEP_DATASET.GEOCODING`
--   WHERE GEO_TYPE = 'CONTRACT_COORDINATES'
--     AND UPPER(COALESCE(REQUEST_LONGITUDE, 'NULL')) != 'NULL'
--     AND UPPER(COALESCE(REQUEST_LATITUDE, 'NULL')) != 'NULL'
-- )
-- SELECT
--   DATE_ADD(appl.partition_date, INTERVAL 1 DAY),
--   cust.cuid,
--   appl.serial_number,
--   appl.created_at,
--   'CONTRACT_COORDINATES',
--   CAST(apply_info.longitude AS STRING),
--   CAST(apply_info.latitude AS STRING),
--   geo_coding.RESPONSE_PLACE_ID,
--   geo_coding.RESPONSE_ADDRESS,
--   geo_coding.RESPONSE_GLOBAL_CODE,
--   geo_coding.RESPONSE_PLACE_TYPES,
--   geo_coding.RESPONSE_LONGITUDE,
--   geo_coding.RESPONSE_LATITUDE,
--   geo_coding.RESPONSE_COUNTRY,
--   geo_coding.RESPONSE_CITY,
--   geo_coding.RESPONSE_DISTRICT,
--   geo_coding.RESPONSE_WARD,
--   geo_coding.RESPONSE_STREET,
--   DATETIME(SAFE_CAST(appl.created_at AS TIMESTAMP), 'UTC'),
--   CURRENT_DATETIME('UTC')
-- FROM latest_hes_application AS appl
-- JOIN latest_hes_customer AS cust
--   ON appl.customer_id = cust.id
-- JOIN latest_vmb_apply_info AS apply_info
--   ON cust.cuid = apply_info.cuid
-- LEFT JOIN geocoding_serial_number_list AS ser_list
--   ON appl.serial_number = ser_list.serial_number
-- LEFT JOIN distinct_coordinates AS geo_coding
--   ON apply_info.longitude = SAFE_CAST(geo_coding.REQUEST_LONGITUDE AS FLOAT64)
--  AND apply_info.latitude = SAFE_CAST(geo_coding.REQUEST_LATITUDE AS FLOAT64)
-- WHERE ser_list.serial_number IS NULL
--   AND geo_coding.REQUEST_LONGITUDE IS NOT NULL
--   AND geo_coding.REQUEST_LATITUDE IS NOT NULL